name: Deploy UAT

on:
  push:
    branches:
      - uat
      - release/*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Create server key
        run: echo "${{ secrets.SF_SERVER_KEY }}" > server.key

      - name: Login UAT
        run: |
          sf org login jwt \
          --client-id ${{ secrets.SF_UAT_CLIENT_ID }} \
          --jwt-key-file server.key \
          --username ${{ secrets.SF_UAT_USERNAME }} \
          --alias uat \
          --instance-url ${{ secrets.SF_INSTANCE_URL }}

      - name: Deploy to UAT
        run: |
          sf project deploy start \
          --target-org uat \
          --source-dir force-app
