name: Deploy DEV

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Create server key
        run: echo "${{ secrets.SF_SERVER_KEY }}" > server.key

      - name: Login DEV
        run: |
          sf org login jwt \
          --client-id ${{ secrets.SF_DEV_CLIENT_ID }} \
          --jwt-key-file server.key \
          --username ${{ secrets.SF_DEV_USERNAME }} \
          --alias dev \
          --instance-url ${{ secrets.SF_INSTANCE_URL }}

      - name: Deploy to DEV
        run: |
          sf project deploy start \
          --target-org dev \
          --source-dir force-app
