name: PR Validation

on:
  pull_request:
    branches:
      - dev
      - uat
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Create server key
        run: echo "${{ secrets.SF_SERVER_KEY }}" > server.key

      - name: Login DEV org
        run: |
          sf org login jwt \
          --client-id ${{ secrets.SF_CLIENT_ID }} \
          --jwt-key-file server.key \
          --username ${{ secrets.SF_DEV_USERNAME }} \
          --alias targetorg \
          --instance-url ${{ secrets.SF_INSTANCE_URL }}

      - name: Validate deployment
        run: |
          sf project deploy start \
          --dry-run \
          --target-org targetorg \
          --source-dir force-app
